# Generated by Django 2.1.15 on 2022-05-02 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_slideshow_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slideshow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Slideshow'),
        ),
    ]
