# Generated by Django 2.1.15 on 2022-04-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220422_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pictures',
            field=models.ManyToManyField(to='core.Picture'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='core.Tag'),
        ),
    ]
