# Generated by Django 2.1.15 on 2022-04-23 19:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220423_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.picture_image_file_path),
        ),
    ]
